sudo: false
language: node_js
node_js:
  - "4"
matrix:
  include:
    - env: UNDERSCORE=1.8 BACKBONE=1.3.2
    - env: LODASH=3.0 BACKBONE=1.2.3
    - env: LODASH=3.1 BACKBONE=1.2.1
    - env: LODASH=4.0 BACKBONE=1.3.2
env: MAINRUN=true
before_install:
  - npm config set ca ""
install:
- curl -L https://rawgit.com/marionettejs/travis-ci-setup/sjs/lodash4-support/ci.sh | bash
after_success:
  - if [[ $MAINRUN == true ]]; then npm run-script coveralls; fi
